services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true

  Pumukit\OpencastBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']

  Pumukit\OpencastBundle\Command\:
    resource: '../../Command/'
    tags: ['console.command']
