services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true

  Pumukit\OpencastBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']

  Pumukit\OpencastBundle\Command\:
    resource: '../../Command/'
    tags: ['console.command']

  Pumukit\OpencastBundle\Services\ClientService:
    class: Pumukit\OpencastBundle\Services\ClientService

  Pumukit\OpencastBundle\Services\OpencastService:
    class: Pumukit\OpencastBundle\Services\OpencastService

  Pumukit\OpencastBundle\Services\SeriesImportService:
    class: Pumukit\OpencastBundle\Services\SeriesImportService

  Pumukit\OpencastBundle\Services\OpencastImportService:
    class: Pumukit\OpencastBundle\Services\OpencastImportService

  Pumukit\OpencastBundle\EventListener\RemoveListener:
    class: Pumukit\OpencastBundle\EventListener\RemoveListener

  Pumukit\OpencastBundle\EventListener\UserListener:
    class: Pumukit\OpencastBundle\EventListener\UserListener

  Pumukit\OpencastBundle\Services\NotificationService:
    class: Pumukit\OpencastBundle\Services\NotificationService

  Pumukit\OpencastBundle\Services\SeriesSyncService:
    class: Pumukit\OpencastBundle\Services\SeriesSyncService

