pumukitopencast_mediapackage_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitopencast.controller.mediapackage:indexAction
        _sylius:
            filterable: true

pumukitopencast_mediapackage_import:
    pattern: /{id}
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitopencast.controller.mediapackage:importAction